### ISSUE TITLE
[FEAT] 공지사항 DB 구축

### ISSUE THREAD

**Issue by hyezis** [hi-sujung/msa-notice#1]
## 📌 이슈 내용

MySQL을 이용한 데이터베이스 개발환경 구축
크롤링한 공지사항 데이터를 저장할 예정

## 💼 작업 목록

- [x] MySQL 사용자 생성 및 GCP 연동
- [x] 데이터베이스 및 테이블 생성
- [x] 크롤링한 공지사항 데이터 저장

**Comment by suhyenim** [comment]
이슈 확인했습니다 :)
